-- require("./custom/lua/*")
require("custom.lua.animations")
require("custom.lua.general")
require("custom.lua.input")
require("custom.lua.keybinds")
require("custom.lua.monitors")
require("custom.lua.window_rules")
