# --------------------------------------------------
# Variables
# --------------------------------------------------
$mainMod = SUPER
$TERMINAL = kitty
$EXPLORER = dolphin
$EDITOR = codium


# --------------------------------------------------
# Signals
# --------------------------------------------------
bind = $mainMod, Q, killactive
bind = $mainMod Shift, Q, forcekillactive
# bind = Alt, Tab, cyclenext,
# bind = Alt, Tab, bringactivetotop
# bind = Alt Shift, Tab, cyclenext, prev
# bind = Alt Shift, Tab, bringactivetotop

bind = $mainMod, F, fullscreen, 0 
bind = $mainMod shift, F, fullscreen, 1
bind = $mainMod, J, layoutmsg, togglesplit
bind = $mainMod Shift, J, layoutmsg, swapsplit
bind = $mainMod, R, layoutmsg, movetoroot
# bind = $mainMod, I, pin


# --------------------------------------------------
# Programs 
# --------------------------------------------------
bind = $mainMod, Return, exec, $TERMINAL 
bind = $mainMod, E, exec, $EXPLORER
bind = $mainMod, C, exec, $EDITOR
bind = $mainMod, T, exec, Telegram 
# bind = $mainMod, D, exec, discord 
bind = $mainMod, O, exec, obs 


# --------------------------------------------------
# Global
# --------------------------------------------------
bind = $mainMod, F10, pass, class:^(com\.obsproject\.Studio)$


# --------------------------------------------------
# Workspaces
# --------------------------------------------------
# navigate to workspace
bind = $mainMod, code:10, workspace, 1
bind = $mainMod, code:11, workspace, 2
bind = $mainMod, code:12, workspace, 3
bind = $mainMod, code:13, workspace, 4
bind = $mainMod, code:14, workspace, 5
bind = $mainMod, code:15, workspace, 6
bind = $mainMod, code:16, workspace, 7
bind = $mainMod, code:17, workspace, 8
bind = $mainMod, code:18, workspace, 9
bind = $mainMod, code:19, workspace, 10
# move focused window to a workspace
bind = $mainMod Shift, code:10, movetoworkspace, 1
bind = $mainMod Shift, code:11, movetoworkspace, 2
bind = $mainMod Shift, code:12, movetoworkspace, 3
bind = $mainMod Shift, code:13, movetoworkspace, 4
bind = $mainMod Shift, code:14, movetoworkspace, 5
bind = $mainMod Shift, code:15, movetoworkspace, 6
bind = $mainMod Shift, code:16, movetoworkspace, 7
bind = $mainMod Shift, code:17, movetoworkspace, 8
bind = $mainMod Shift, code:18, movetoworkspace, 9
bind = $mainMod Shift, code:19, movetoworkspace, 10
# move focused window to a workspace silently
bind = $mainMod Alt, code:10, movetoworkspacesilent, 1
bind = $mainMod Alt, code:11, movetoworkspacesilent, 2
bind = $mainMod Alt, code:12, movetoworkspacesilent, 3
bind = $mainMod Alt, code:13, movetoworkspacesilent, 4
bind = $mainMod Alt, code:14, movetoworkspacesilent, 5
bind = $mainMod Alt, code:15, movetoworkspacesilent, 6
bind = $mainMod Alt, code:16, movetoworkspacesilent, 7
bind = $mainMod Alt, code:17, movetoworkspacesilent, 8
bind = $mainMod Alt, code:18, movetoworkspacesilent, 9
bind = $mainMod Alt, code:19, movetoworkspacesilent, 10
