# focus on apps
windowrule = focus_on_activate on, match:class firefox
windowrule = focus_on_activate on, match:class code-oss
windowrule = focus_on_activate on, match:class codium

# opacity
windowrule = opacity 0.9 override 0.9 override, match:class firefox 
windowrule = opacity 0.9 override 0.9 override, match:class chromium

# tearing
windowrule = match:class dota2, immediate yes